// Code generated by MockGen. DO NOT EDIT.
// Source: throttler.go
//
// Generated by this command:
//
//	mockgen -source=throttler.go -destination=throttler_mock.go -package=throttler
//

// Package throttler is a generated GoMock package.
package throttler

import (
	reflect "reflect"

	inter "github.com/panoptisDev/pano/inter"
	opera "github.com/panoptisDev/pano/opera"
	idx "github.com/Fantom-foundation/lachesis-base/inter/idx"
	pos "github.com/Fantom-foundation/lachesis-base/inter/pos"
	gomock "go.uber.org/mock/gomock"
)

// MockWorldReader is a mock of WorldReader interface.
type MockWorldReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorldReaderMockRecorder
	isgomock struct{}
}

// MockWorldReaderMockRecorder is the mock recorder for MockWorldReader.
type MockWorldReaderMockRecorder struct {
	mock *MockWorldReader
}

// NewMockWorldReader creates a new mock instance.
func NewMockWorldReader(ctrl *gomock.Controller) *MockWorldReader {
	mock := &MockWorldReader{ctrl: ctrl}
	mock.recorder = &MockWorldReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldReader) EXPECT() *MockWorldReaderMockRecorder {
	return m.recorder
}

// GetEpochValidators mocks base method.
func (m *MockWorldReader) GetEpochValidators() (*pos.Validators, idx.Epoch) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochValidators")
	ret0, _ := ret[0].(*pos.Validators)
	ret1, _ := ret[1].(idx.Epoch)
	return ret0, ret1
}

// GetEpochValidators indicates an expected call of GetEpochValidators.
func (mr *MockWorldReaderMockRecorder) GetEpochValidators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochValidators", reflect.TypeOf((*MockWorldReader)(nil).GetEpochValidators))
}

// GetLastEvent mocks base method.
func (m *MockWorldReader) GetLastEvent(arg0 idx.ValidatorID) *inter.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastEvent", arg0)
	ret0, _ := ret[0].(*inter.Event)
	return ret0
}

// GetLastEvent indicates an expected call of GetLastEvent.
func (mr *MockWorldReaderMockRecorder) GetLastEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastEvent", reflect.TypeOf((*MockWorldReader)(nil).GetLastEvent), arg0)
}

// GetRules mocks base method.
func (m *MockWorldReader) GetRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetRules indicates an expected call of GetRules.
func (mr *MockWorldReaderMockRecorder) GetRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockWorldReader)(nil).GetRules))
}
