# Copyright 2025 Pano Operations Ltd
# This file is part of the Pano Client
#
# Pano is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pano is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Pano. If not, see <http://www.gnu.org/licenses/>.

# default coverage setting
coverage:
  range: 50..80 # below 50 is red, between 50-80 is yellow and above 80 is green
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 80% # coverage of the changes
        threshold: 1% # allow the coverage to drop by <threshold>%
ignore:
  - "tests/"
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*_abigen.go"
  - "**/*.pb.go"
