// Code generated by MockGen. DO NOT EDIT.
// Source: emitter.go
//
// Generated by this command:
//
//	mockgen -source=emitter.go -destination=emitter_mock.go -package=emitter
//

// Package emitter is a generated GoMock package.
package emitter

import (
	big "math/big"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBaseFeeSource is a mock of BaseFeeSource interface.
type MockBaseFeeSource struct {
	ctrl     *gomock.Controller
	recorder *MockBaseFeeSourceMockRecorder
	isgomock struct{}
}

// MockBaseFeeSourceMockRecorder is the mock recorder for MockBaseFeeSource.
type MockBaseFeeSourceMockRecorder struct {
	mock *MockBaseFeeSource
}

// NewMockBaseFeeSource creates a new mock instance.
func NewMockBaseFeeSource(ctrl *gomock.Controller) *MockBaseFeeSource {
	mock := &MockBaseFeeSource{ctrl: ctrl}
	mock.recorder = &MockBaseFeeSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseFeeSource) EXPECT() *MockBaseFeeSourceMockRecorder {
	return m.recorder
}

// GetCurrentBaseFee mocks base method.
func (m *MockBaseFeeSource) GetCurrentBaseFee() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBaseFee")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GetCurrentBaseFee indicates an expected call of GetCurrentBaseFee.
func (mr *MockBaseFeeSourceMockRecorder) GetCurrentBaseFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBaseFee", reflect.TypeOf((*MockBaseFeeSource)(nil).GetCurrentBaseFee))
}
