// Code generated by MockGen. DO NOT EDIT.
// Source: tx_pool.go
//
// Generated by this command:
//
//	mockgen -source=tx_pool.go -destination=tx_pool_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	big "math/big"
	reflect "reflect"

	state "github.com/panoptisDev/pano/inter/state"
	opera "github.com/panoptisDev/pano/opera"
	common "github.com/ethereum/go-ethereum/common"
	event "github.com/ethereum/go-ethereum/event"
	params "github.com/ethereum/go-ethereum/params"
	gomock "go.uber.org/mock/gomock"
)

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockStateReader) Block(hash common.Hash, number uint64) *EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", hash, number)
	ret0, _ := ret[0].(*EvmBlock)
	return ret0
}

// Block indicates an expected call of Block.
func (mr *MockStateReaderMockRecorder) Block(hash, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockStateReader)(nil).Block), hash, number)
}

// CurrentBaseFee mocks base method.
func (m *MockStateReader) CurrentBaseFee() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBaseFee")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// CurrentBaseFee indicates an expected call of CurrentBaseFee.
func (mr *MockStateReaderMockRecorder) CurrentBaseFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBaseFee", reflect.TypeOf((*MockStateReader)(nil).CurrentBaseFee))
}

// CurrentBlock mocks base method.
func (m *MockStateReader) CurrentBlock() *EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBlock")
	ret0, _ := ret[0].(*EvmBlock)
	return ret0
}

// CurrentBlock indicates an expected call of CurrentBlock.
func (mr *MockStateReaderMockRecorder) CurrentBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBlock", reflect.TypeOf((*MockStateReader)(nil).CurrentBlock))
}

// CurrentConfig mocks base method.
func (m *MockStateReader) CurrentConfig() *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentConfig")
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// CurrentConfig indicates an expected call of CurrentConfig.
func (mr *MockStateReaderMockRecorder) CurrentConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentConfig", reflect.TypeOf((*MockStateReader)(nil).CurrentConfig))
}

// CurrentMaxGasLimit mocks base method.
func (m *MockStateReader) CurrentMaxGasLimit() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentMaxGasLimit")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// CurrentMaxGasLimit indicates an expected call of CurrentMaxGasLimit.
func (mr *MockStateReaderMockRecorder) CurrentMaxGasLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentMaxGasLimit", reflect.TypeOf((*MockStateReader)(nil).CurrentMaxGasLimit))
}

// CurrentRules mocks base method.
func (m *MockStateReader) CurrentRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// CurrentRules indicates an expected call of CurrentRules.
func (mr *MockStateReaderMockRecorder) CurrentRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentRules", reflect.TypeOf((*MockStateReader)(nil).CurrentRules))
}

// CurrentStateDB mocks base method.
func (m *MockStateReader) CurrentStateDB() (state.StateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentStateDB")
	ret0, _ := ret[0].(state.StateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentStateDB indicates an expected call of CurrentStateDB.
func (mr *MockStateReaderMockRecorder) CurrentStateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentStateDB", reflect.TypeOf((*MockStateReader)(nil).CurrentStateDB))
}

// Header mocks base method.
func (m *MockStateReader) Header(hash common.Hash, number uint64) *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", hash, number)
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockStateReaderMockRecorder) Header(hash, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockStateReader)(nil).Header), hash, number)
}

// SubscribeNewBlock mocks base method.
func (m *MockStateReader) SubscribeNewBlock(ch chan<- ChainHeadNotify) event.Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNewBlock", ch)
	ret0, _ := ret[0].(event.Subscription)
	return ret0
}

// SubscribeNewBlock indicates an expected call of SubscribeNewBlock.
func (mr *MockStateReaderMockRecorder) SubscribeNewBlock(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNewBlock", reflect.TypeOf((*MockStateReader)(nil).SubscribeNewBlock), ch)
}
