#!/bin/bash

echo "========================================="
echo "   8-Hour Stress Test - Starting Guide"
echo "========================================="
echo ""
echo "✅ Pre-flight checks passed:"
echo "   - User 4 wallet: 0xE56E6757b8D4124B235436a246af5DCB0a69D14D"
echo "   - Balance: ~87,160 PANO (sufficient ✅)"
echo "   - Test transaction: SUCCESS ✅"
echo ""
echo "📊 Test Configuration:"
echo "   - Duration: 8 hours"
echo "   - Batches: 48 (every 10 minutes)"
echo "   - Transactions: 480 total (10 per batch)"
echo "   - Cost: ~4.8 PANO + gas fees"
echo ""
echo "Choose how to run:"
echo ""
echo "1️⃣  RECOMMENDED - Run in tmux (detachable session):"
echo "   tmux new -s stress8h"
echo "   cd /home/regium/pano/smart-contracts"
echo "   node ../testnet/8hour-stress-test.mjs"
echo "   # Press Ctrl+B then D to detach"
echo "   # Reattach: tmux attach -t stress8h"
echo ""
echo "2️⃣  Run in background with nohup:"
echo "   cd /home/regium/pano/smart-contracts"
echo "   nohup node ../testnet/8hour-stress-test.mjs > ../testnet/stress-output.log 2>&1 &"
echo "   tail -f ../testnet/stress-output.log"
echo ""
echo "3️⃣  Run in foreground (terminal must stay open):"
echo "   cd /home/regium/pano/smart-contracts"
echo "   node ../testnet/8hour-stress-test.mjs"
echo ""
echo "📈 Monitor progress:"
echo "   watch -n 30 'cat /home/regium/pano/testnet/8hour-stress-stats.json | jq .'"
echo ""
echo "🛑 Stop test:"
echo "   Press Ctrl+C (graceful shutdown with summary)"
echo ""
echo "========================================="
echo ""

read -p "Start the test now in tmux? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Starting tmux session 'stress8h'..."
    tmux new -s stress8h "cd /home/regium/pano/smart-contracts && node ../testnet/8hour-stress-test.mjs"
fi
